CREATE DATABASE PRUEBA_ECOMMERCE;
USE PRUEBA_ECOMMERCE;
CREATE TABLE CATEGORIA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(150) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE LOCALIDAD (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	COORDENADAS VARCHAR(40) NOT NULL,
	UBICACION VARCHAR(150) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);


CREATE TABLE TIPOUSUARIO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE OFERTAESPECIAL (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDCATEGORIA INT NOT NULL,
	FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(ID),
    PRECIO INT NOT NULL,
    FECHAINICIO DATETIME NOT NULL,
    FECHAFIN DATETIME NOT NULL,
    TIPOPUBLICIDAD INT NOT NULL,
    TIPOOFERTA INT NOT NULL,
	URLIMGTILE VARCHAR(200) NOT NULL,
	URLIMGCOVER VARCHAR(200) NOT NULL,
	RAZON VARCHAR(200) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE PRODUCTO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDLOCALIDAD INT NOT NULL,
	FOREIGN KEY (IDLOCALIDAD) REFERENCES LOCALIDAD(ID),
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(150) NOT NULL,
    FECHACREACION DATETIME NOT NULL,
	PRECIO INT NOT NULL,
    DESCUENTO DECIMAL(10,2) NOT NULL,
    CANTDISPONIBLE INT NOT NULL,
	URLIMAGEN VARCHAR(200) NOT NULL,
	HASDESCUENTO BOOLEAN NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE HORARIO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDLOCALIDAD INT NOT NULL,
	FOREIGN KEY (IDLOCALIDAD) REFERENCES LOCALIDAD(ID),
	NOMBRE VARCHAR(50) NOT NULL,
	DURACIONHORARIO INT NOT NULL,
	TIPOHORARIO INT NOT NULL,
	ISDEFAULT BOOLEAN NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE USUARIO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDTIPO INT NOT NULL,
	FOREIGN KEY (IDTIPO) REFERENCES TIPOUSUARIO(ID),
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDOS VARCHAR(60) NOT NULL,
	CEDULA VARCHAR(20) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
    FECHACREACION DATETIME NOT NULL,
	TWOFA BOOLEAN NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE PRODUCTOSOFERTA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUCTO INT NOT NULL,
	FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID),
	IDOFERTAESPECIAL INT NOT NULL,
	FOREIGN KEY (IDOFERTAESPECIAL) REFERENCES OFERTAESPECIAL(ID),
    DESCUENTO DECIMAL(10,2) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE CATEGORIAPRODUCTO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUCTO INT NOT NULL,
	FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID),
	IDCATEGORIA INT NOT NULL,
	FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(ID),
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE DIA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDHORARIO INT NOT NULL,
	FOREIGN KEY (IDHORARIO) REFERENCES HORARIO(ID),
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(150) NOT NULL,
	NUMDIA INT NOT NULL,
    HORAINICIO DATETIME NOT NULL,
    HORAFINAL DATETIME NOT NULL,
    HORAINICIOALMUERZO DATETIME NOT NULL,
    HORAFINALALMUERZO DATETIME NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE ENVIO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT NOT NULL,
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
	CANTIDAD INT NOT NULL,
	TIPOENVIO INT NOT NULL,
	COORDENADASENVIO VARCHAR(30) NOT NULL,
	UBICACIONENVIO VARCHAR(150) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE UBICACION (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT NOT NULL,
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
	NOMBRE VARCHAR(50) NOT NULL,
	COORDENADAS VARCHAR(30) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE CREDENCIALES (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	PASS VARCHAR(100) NOT NULL,
	TOKEN VARCHAR(50) NOT NULL,
	IDUSUARIO INT NOT NULL,
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE GUARDADO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT NOT NULL,
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
	IDPRODUCTO INT NOT NULL,
	FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID),
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);



CREATE TABLE SOLICITUDVENTA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT NOT NULL,
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
	IDENVIO INT NOT NULL,
	FOREIGN KEY (IDENVIO) REFERENCES ENVIO(ID),
	TIPOVENTA INT NOT NULL,
    FECHASOLICITUD DATETIME NOT NULL,
    FECHAAPROVACION DATETIME NOT NULL,
	URLCOMPROBANTE VARCHAR(200) NOT NULL,
	ENVIO BOOLEAN NOT NULL,
	ESTADOSOLICITUD BOOLEAN NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE VENTADETALLE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUCTO INT NOT NULL,
	FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID),
	IDVENTA INT NOT NULL,
	FOREIGN KEY (IDVENTA) REFERENCES SOLICITUDVENTA(ID),
	CANTIDAD INT NOT NULL
);

CREATE TABLE CARRITO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT NOT NULL,
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
	IDPRODUCTO INT NOT NULL,
	FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(ID),
	CANTIDAD INT NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);


