CREATE TABLE ENCABEZADO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CODIGOACTIVIDAD VARCHAR(6) NOT NULL,
	CLAVE VARCHAR(50) NOT NULL,
	NUMEROCONSECUTIVO VARCHAR(20) NOT NULL,
	FECHAEMISION DATETIME NOT NULL,
	IDEMISOR INT NOT NULL,
	IDRECEPTOR INT NOT NULL,
	CONDICIONVENTA VARCHAR(2) NOT NULL,
	PLAZOCREDITO VARCHAR(10),
	MEDIOPAGO VARCHAR(8) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1,
	FOREIGN KEY (IDEMISOR) REFERENCES USUARIO(ID),
	FOREIGN KEY (IDRECEPTOR) REFERENCES RECEPTOR(ID)
);



CREATE TABLE CATEGORIA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(150) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE LOCALIDAD (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	COORDENADAS VARCHAR(30) NOT NULL,
	UBICACION VARCHAR(150) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);


CREATE TABLE TIPOUSUARIO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	ESTADO BOOLEAN NOT NULL DEFAULT 1
);












CREATE TABLE CREDENCIALES (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	PASS VARCHAR(100) NOT NULL,
	TOKEN VARCHAR(50) NOT NULL,
	IDUSUARIO INT NOT NULL,
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
);

CREATE TABLE TIPOUSUARIO (
	ID INT PRIMARY KEY AUTO_INCREMENT,



	ESTADO BOOLEAN NOT NULL DEFAULT 1
);